#include <iostream.h>
#include <fstream.h>

// App structure
// funckja Load - wczytująca dane z pliku do tablicy tab - tablicy obiektów klasy student.
void Load(void) {
    int i = 0;
    int r = 0;
    ifstream plik;
    plik.open("baza.txt");
    do {
        if(plik.fail()) // jesli plik nie zostal utworzony
        {
            plik.close(); return; // koniec sesji
        }

        if(!plik.eof()) // to avoid the error generated by attempting to get input past the end of a file
        {
            getline(plik, tab[i].imie, '#');
            getline(plik, tab[i].adres, '#');
            getline(plik, tab[i].tel, '#');

            plik.ignore();
            i++;
            if(i == MAX) break; // zakonc while - brak miejsc
        }
        while (!plik.eof()); 
        cout << "\n Rozmiar tablicy: " <<i<<endl;
            plik.close();
    }

}

void Save(void) // funk wczytujaca dane z pliku do tablicy student
{
    int i;
    ofstream plik;
    plik.open("baza.txt");
    if(plik.fail())
    {
        plik.close();
        if(plik.fail());
        cout << "Wystapil blad pliku!" <<endl;
        exit(1)
    }    
    for(int i = 0; i < MAX; i++)
        if(tab[i].imie != "")
        {
            plik << tab[i].imie << "#"
                << tab[i].adres << "#"
                << tab[i].tel << "#" << endl;
        }
    plik.close();
}


void main (void) {
    Load();
    
    Save()
}
