USE [pavlovskyim]
GO

/****** Object:  Table [dbo].[ORDER]    Script Date: 24.03.2025 12:04:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ORDER](
	[id_order] [int] NOT NULL,
	[id_client] [int] NOT NULL,
	[order_date] [date] NOT NULL,
 CONSTRAINT [PK_ORDER] PRIMARY KEY CLUSTERED 
(
	[id_order] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ORDER]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_ORDER] FOREIGN KEY([id_order])
REFERENCES [dbo].[ORDER] ([id_order])
GO

ALTER TABLE [dbo].[ORDER] CHECK CONSTRAINT [FK_ORDER_ORDER]
GO



ALTER  TABLE [dbo].[ORDER]
ADD CONSTRAINT FK_Order_Client
FOREIGN KEY (id_client) REFERENCES CLIENT(id_client);
