USE [pavlovskyim]
GO

/****** Object:  Table [dbo].[PRODUCTS]    Script Date: 24.03.2025 11:31:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
/*
CREATE TABLE [dbo].[PRODUCTS](
	[id_product] [int] NOT NULL,
	[product_name] [char](30) NOT NULL,
 CONSTRAINT [PK_PRODUCTS] PRIMARY KEY CLUSTERED 
(
	[id_product] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
*/


ALTER TABLE [dbo].[PRODUCTS] 
ADD 
	[price] [decimal](10,2) NOT NULL DEFAULT 0;

